language: node_js
node_js:
  - "8"
  - "7"
  - "6"
matrix:
  allow_failures:
    - node_js: "7"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

notifications:
  email: false
